# Generated by Django 5.1.7 on 2025-05-27 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("supplies", "0002_review"),
    ]

    operations = [
        migrations.AddField(
            model_name="supplies",
            name="stock",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
