# Generated by Django 5.1.7 on 2025-05-27 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("supplies", "0003_supplies_stock"),
    ]

    operations = [
        migrations.AlterField(
            model_name="supplies",
            name="stock",
            field=models.IntegerField(default=0),
        ),
    ]
