# Generated by Django 5.1.7 on 2025-05-27 10:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("supplies", "0004_alter_supplies_stock"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="supplies",
            name="stock",
        ),
    ]
