# Generated by Django 5.1.7 on 2025-05-27 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("supplies", "0006_supplies_stock"),
    ]

    operations = [
        migrations.AddField(
            model_name="supplies",
            name="total_stock",
            field=models.IntegerField(default=0),
        ),
    ]
