# Generated by Django 5.1.7 on 2025-05-28 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("supplies", "0008_remove_supplies_stock_remove_supplies_total_stock"),
    ]

    operations = [
        migrations.AddField(
            model_name="supplies",
            name="stock",
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="supplies",
            name="total_stock",
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
