# Generated by Django 5.1.7 on 2025-05-28 05:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("supplies", "0009_supplies_stock_supplies_total_stock"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="supplies",
            name="stock",
        ),
        migrations.RemoveField(
            model_name="supplies",
            name="total_stock",
        ),
    ]
